### ISSUE TITLE
How to persist snippets without having to re-import them? 

### ISSUE THREAD

**Issue by kings2u** [lochidev/TextComparePro#10]
Is there an option to persist snippets across sessions? Every time I add a new snippet I back up everything for fear of losing them, as has happened a few times in the past. I’m not sure if I’m missing an obvious option, so thought I’d ask.

Thank you for addressing my previous feature requests! This is the best snippet manager on Android.

**Comment by kings2u** [comment]
Oh, is it just a matter of clicking "Make sure to save" after I add new snippets? I feel stupid. I didn’t realize it was a button, haha.

**Comment by lochidev** [comment]
Yep! I could add auto-save but the reason I didn't was because if someone accidentally imported a file like the https://github.com/espanso/hub/tree/main/packages/actually-all-emojis/0.1.0 with 3.7k triggers, it will be hard to delete everything one by one 😅 I'll close the issue now if you have more feedback feel free to re-open 💜
