### ISSUE TITLE
Issue with line breaks causing text expansion not to work correctly

### ISSUE THREAD

**Issue by urmomseksy** [lochidev/TextComparePro#2]
I have tried this with two different document apps. Markor and Notes from Fdroid.

To replicate:

- on first line of document, type the shortcut and the text expansion works
- add a space after the text expansion and type the shortcut and text expansion still works
- if you press enter / return on the device keyboard then try to type a shortcut, text expansion will not work.

**Comment by lochidev** [comment]
Nice catch! Yeah for now I was splitting up the words by space, to check if the user has it in their dictionary. It's a bit tricky though because I don't want to use too much CPU power, but I guess it's already negligible so I'll find a way to split this up into two words in the next update. In the meantime, adding a space before the newline word seems to work. "word1\nword2" won't get split but "word1 word2" will be. I never could've seen this coming 😂 Thank you for reporting it. If you are a developer feel free to open a PR if you want to contribute.

**Comment by lochidev** [comment]
Fixed with the latest commits. v6.1 should have this fixed when released💜
